"""Tests for the i18n module (PO/gettext runtime + provider seam).

The runtime is exercised against a small fixture catalog (``_UK_PO`` /
``_EN_PO``), not the framework's real ``locales/`` - that one is regenerated by
``grunt i18n extract`` and its content changes with the code.
"""

from pathlib import Path

import pytest

import grunt.i18n.service as svc
from grunt.i18n import LANGUAGE_OPTIONS_SOURCE, _, ngettext, pgettext
from grunt.i18n.meta import translate_doctype_meta
from grunt.i18n.plurals import plural_form_count, plural_index
from grunt.i18n.service import TranslationService, _parse_po_file, translation_service
from grunt.metadata.dynamic_options import get_option_labels, get_options

REAL_LOCALES_DIR = Path(__file__).parent.parent / "locales"

_HEADER = """msgid ""
msgstr ""
"Content-Type: text/plain; charset=UTF-8\\n"

"""

_UK_PO = (
    _HEADER
    + """msgid "Document not found"
msgstr "Документ не знайдено"

msgid "Yes"
msgstr "Так"

msgctxt "button"
msgid "Save"
msgstr "Зберегти"

msgctxt "button"
msgid "Delete"
msgstr "Видалити"

msgctxt "label"
msgid "Search"
msgstr "Пошук"

msgid "Search"
msgstr "Шукати"

msgid "%(count)d document"
msgid_plural "%(count)d documents"
msgstr[0] "%(count)d документ"
msgstr[1] "%(count)d документи"
msgstr[2] "%(count)d документів"

msgid "%(count)d record"
msgid_plural "%(count)d records"
msgstr[0] "%(count)d запис"
msgstr[1] "%(count)d записи"
msgstr[2] "%(count)d записів"

#~ msgid "Obsolete string"
#~ msgstr "Застарілий рядок"
"""
)

_EN_PO = (
    _HEADER
    + """msgid "Країна"
msgstr "Country"

msgid "Назва"
msgstr "Name"
"""
)


@pytest.fixture(autouse=True)
def fixture_catalog(tmp_path, monkeypatch):
    """Point the translation service at the fixture catalog, no app catalogs."""
    for lang, text in (("uk", _UK_PO), ("en", _EN_PO)):
        po_dir = tmp_path / lang / "LC_MESSAGES"
        po_dir.mkdir(parents=True)
        (po_dir / "grunt.po").write_text(text, encoding="utf-8")

    monkeypatch.setattr(svc, "_LOCALE_DIR", tmp_path)
    monkeypatch.setattr(svc, "_app_locale_po_files", lambda _lang: [])
    monkeypatch.setattr(svc, "_app_locale_codes", set)
    translation_service.reload()
    yield tmp_path
    monkeypatch.undo()
    translation_service.reload()


class TestPoParser:
    def test_real_catalogs_parse(self):
        # Sources are English, so the real `en` catalog may legitimately be empty.
        uk = _parse_po_file(REAL_LOCALES_DIR / "uk" / "LC_MESSAGES" / "grunt.po")
        assert len(uk) > 100
        assert isinstance(
            _parse_po_file(REAL_LOCALES_DIR / "en" / "LC_MESSAGES" / "grunt.po"), dict
        )

    def test_parse_uk_po(self, fixture_catalog):
        po_path = fixture_catalog / "uk" / "LC_MESSAGES" / "grunt.po"
        catalog = _parse_po_file(po_path)

        # Simple translation
        assert catalog["Document not found"] == "Документ не знайдено"
        assert catalog["Yes"] == "Так"

        # Context-aware translation
        assert catalog["button\x04Save"] == "Зберегти"
        assert catalog["button\x04Delete"] == "Видалити"
        assert catalog["label\x04Search"] == "Пошук"

    def test_obsolete_entries_are_ignored(self, fixture_catalog):
        catalog = _parse_po_file(fixture_catalog / "uk" / "LC_MESSAGES" / "grunt.po")
        assert "Obsolete string" not in catalog

    def test_parse_plural_forms(self, fixture_catalog):
        po_path = fixture_catalog / "uk" / "LC_MESSAGES" / "grunt.po"
        catalog = _parse_po_file(po_path)

        # Plural forms stored as msgid\x00index
        assert catalog["%(count)d document\x000"] == "%(count)d документ"
        assert catalog["%(count)d document\x001"] == "%(count)d документи"
        assert catalog["%(count)d document\x002"] == "%(count)d документів"


class TestTranslationService:
    def setup_method(self):
        self.svc = TranslationService()
        self.svc.reload()  # Clear cache

    def test_translate_uk(self):
        result = self.svc.translate("Document not found", lang="uk")
        assert result == "Документ не знайдено"

    def test_translate_en_falls_back_to_source(self):
        # English framework msgids have no `en` entry -> returned unchanged.
        assert self.svc.translate("Document not found", lang="en") == "Document not found"

    def test_translate_en_uses_po(self):
        # Ukrainian-source labels DO get translated for `en`.
        assert self.svc.translate("Країна", lang="en") == "Country"

    def test_pgettext_falls_back_to_context_free_entry(self):
        # No `meta:Foo.bar` entry, but a plain "Назва" -> "Name" exists.
        assert self.svc.pgettext("meta:Foo.bar", "Назва", lang="en") == "Name"

    def test_translate_missing_returns_source(self):
        result = self.svc.translate("This string has no translation", lang="uk")
        assert result == "This string has no translation"

    def test_pgettext(self):
        result = self.svc.pgettext("button", "Save", lang="uk")
        assert result == "Зберегти"

    def test_pgettext_different_context(self):
        result = self.svc.pgettext("label", "Search", lang="uk")
        assert result == "Пошук"

    def test_ngettext_singular(self):
        result = self.svc.ngettext("%(count)d document", "%(count)d documents", 1, lang="uk")
        assert result == "%(count)d документ"

    def test_ngettext_few(self):
        result = self.svc.ngettext("%(count)d document", "%(count)d documents", 3, lang="uk")
        assert result == "%(count)d документи"

    def test_ngettext_many(self):
        result = self.svc.ngettext("%(count)d document", "%(count)d documents", 5, lang="uk")
        assert result == "%(count)d документів"

    def test_ngettext_format(self):
        count = 5
        result = self.svc.ngettext(
            "%(count)d document", "%(count)d documents", count, lang="uk"
        ) % {"count": count}
        assert result == "5 документів"

    def test_get_all_translations(self):
        all_trans = self.svc.get_all_translations("uk")
        assert isinstance(all_trans, dict)
        assert "Document not found" in all_trans
        assert all_trans["Document not found"] == "Документ не знайдено"


class TestRuntimeProvider:
    def teardown_method(self):
        # Drop the test provider so it can't leak into other tests.

        svc._provider = None
        translation_service.invalidate()

    def test_provider_beats_po_and_source(self):
        translation_service.register_provider(
            lambda locale: {"Brand new string": "З провайдера"} if locale == "uk" else {}
        )
        assert translation_service.translate("Brand new string", lang="uk") == "З провайдера"
        # PO still wins where the provider is silent
        assert (
            translation_service.translate("Document not found", lang="uk") == "Документ не знайдено"
        )

    def test_provider_context_key(self):
        translation_service.register_provider(lambda _l: {"meta:Foo|Bar": "Бар"})
        assert translation_service.pgettext("meta:Foo", "Bar", lang="uk") == "Бар"

    def test_provider_included_in_bundle(self):
        translation_service.register_provider(lambda _l: {"Bundle key": "У бандлі"})
        assert translation_service.get_all_translations("uk")["Bundle key"] == "У бандлі"

    def test_invalidate_bumps_version(self):
        before = translation_service.catalog_version("uk")
        translation_service.invalidate()
        assert translation_service.catalog_version("uk") != before


class TestMetaTranslation:
    def teardown_method(self):
        svc._provider = None
        translation_service.invalidate()

    def _dt(self) -> dict:
        return {
            "name": "Widget",
            "label": "Віджет",
            "description": "Опис",
            "fields": [
                {
                    "fieldname": "status",
                    "label": "Статус",
                    "description": "Стан віджета",
                    "placeholder": "Оберіть…",
                    "fieldtype": "Select",
                    "options": "Новий\nЗакритий",
                    "translatable": True,
                },
                {"fieldname": "kind", "fieldtype": "Select", "options": "Новий|Star\nІнший"},
                {"fieldname": "note", "label": "Нотатка", "fieldtype": "Text"},
            ],
            "status_indicators": [{"value": "Новий", "label": "Новий"}],
        }

    def test_description_and_placeholder_use_own_contexts(self):
        translation_service.register_provider(
            lambda _l: {
                "help:Widget.status|Стан віджета": "Widget state",
                "hint:Widget.status|Оберіть…": "Choose…",
            }
        )
        out = translate_doctype_meta(self._dt(), lang="uk")
        assert out["fields"][0]["description"] == "Widget state"
        assert out["fields"][0]["placeholder"] == "Choose…"
        assert out["fields"][0]["label"] == "Статус"  # label context untouched

    def test_translates_label_field_and_options(self):
        translation_service.register_provider(
            lambda _l: {
                "meta:Widget|Віджет": "Widget",
                "meta:Widget.status|Статус": "Status",
                "select:Widget.status|Новий": "New",
                "status:Widget|Новий": "New",
            }
        )
        out = translate_doctype_meta(self._dt(), lang="uk")

        assert out["label"] == "Widget"
        assert out["fields"][0]["label"] == "Status"
        # Values are what gets stored - only the captions are translated.
        assert out["fields"][0]["options"] == "Новий\nЗакритий"
        assert out["fields"][0]["option_labels"] == {"Новий": "New"}
        assert out["fields"][2]["label"] == "Нотатка"  # untranslated -> source kept
        assert out["status_indicators"][0]["label"] == "New"

    def test_noop_without_entries(self):
        out = translate_doctype_meta(self._dt(), lang="uk")
        assert out["label"] == "Віджет"
        assert out["fields"][0]["options"] == "Новий\nЗакритий"
        assert "option_labels" not in out["fields"][0]

    def test_non_translatable_select_is_left_alone(self):
        # A context-free "Новий" must not leak into a plain Select's options.
        translation_service.register_provider(lambda _l: {"Новий": "New"})
        out = translate_doctype_meta(self._dt(), lang="uk")
        assert out["fields"][0]["option_labels"] == {"Новий": "New"}
        assert out["fields"][1]["options"] == "Новий|Star\nІнший"
        assert "option_labels" not in out["fields"][1]


class TestPlurals:
    def teardown_method(self):
        svc._provider = None
        translation_service.invalidate()

    def test_plural_index_rules(self):
        assert plural_form_count("uk") == 3
        assert plural_form_count("en") == 2
        assert [plural_index("uk", n) for n in (1, 2, 5, 11, 21, 22)] == [0, 1, 2, 2, 0, 1]
        assert [plural_index("en", n) for n in (1, 2, 5)] == [0, 1, 1]

    def test_ngettext_from_po(self):
        # The core uk PO ships "%(count)d document" plural forms.
        svc = TranslationService()
        assert svc.ngettext("%(count)d document", "%(count)d documents", 1, lang="uk") == (
            "%(count)d документ"
        )
        assert svc.ngettext("%(count)d document", "%(count)d documents", 5, lang="uk") == (
            "%(count)d документів"
        )

    def test_ngettext_from_provider(self):
        translation_service.register_provider(
            lambda _l: {
                "{n} apple\x000": "{n} яблуко",
                "{n} apple\x001": "{n} яблука",
                "{n} apple\x002": "{n} яблук",
            }
        )
        f = lambda n: translation_service.ngettext("{n} apple", "{n} apples", n, lang="uk")  # noqa: E731
        assert (f(1), f(3), f(5)) == ("{n} яблуко", "{n} яблука", "{n} яблук")

    def test_plural_keys_reach_bundle(self):
        translation_service.register_provider(lambda _l: {"{n} file\x001": "{n} файли"})
        assert translation_service.get_all_translations("uk")["{n} file\x001"] == "{n} файли"


class TestSupportedLangs:
    def test_defaults_present(self):
        assert {"uk", "en"} <= translation_service.supported_langs()

    def test_set_supported_keeps_defaults_and_normalizes(self):
        translation_service.set_supported(["de-DE", "FR", "uk"])
        langs = translation_service.supported_langs()
        assert {"de", "fr", "uk", "en"} <= langs
        translation_service.set_supported(["uk", "en"])  # restore


class TestUiLanguages:
    def test_discovered_from_po_catalogs(self, fixture_catalog):
        assert translation_service.ui_languages() == ["en", "uk"]
        (fixture_catalog / "pl" / "LC_MESSAGES").mkdir(parents=True)
        (fixture_catalog / "pl" / "LC_MESSAGES" / "grunt.po").write_text(_EN_PO, encoding="utf-8")
        translation_service.reload()
        assert translation_service.ui_languages() == ["en", "pl", "uk"]
        assert "pl" in translation_service.supported_langs()

    def test_provider_extras_and_names(self, monkeypatch):
        monkeypatch.setattr(svc, "_extra_ui_langs", set())
        translation_service.add_ui_languages(["de-DE"])
        assert "de" in translation_service.ui_languages()
        translation_service.set_language_names({"de": "Deutsch"})
        assert translation_service.language_name("de") == "Deutsch"
        assert translation_service.language_name("xx") == "xx"

    def test_language_select_options(self):
        translation_service.set_language_names({"uk": "Українська"})
        assert get_options(LANGUAGE_OPTIONS_SOURCE) == ["en", "uk"]
        assert get_option_labels(LANGUAGE_OPTIONS_SOURCE)["uk"] == "Українська"


class TestConvenienceFunctions:
    def test_underscore_function(self):
        from grunt.i18n.service import translation_service

        translation_service.set_lang("uk")
        assert _("Document not found") == "Документ не знайдено"
        assert pgettext("button", "Save") == "Зберегти"

        result = ngettext("%(count)d record", "%(count)d records", 2) % {"count": 2}
        assert result == "2 записи"
